import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import LandBanner from '../components/LandBanner'
import ExploreCards from '../components/ExploreCards'
import OptionCards from '../components/OptionCards'
import LargeCard from '../components/LargeCard'
import TheFooter from '../components/TheFooter'

const inter = Inter({ subsets: ['latin'] })

export default function Home({explore, exploreBigCards}) {
  return (
    <div className=''>
      <Head>
        <title>airbnb cl</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header/>
    <LandBanner />
    <main className='max-w-6xl px-3 mx-auto'>
      <section className='py-4'>
        <h2 className='font-bold text-3xl py-4'>explore nearby place.</h2>
        <div className='grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
          {explore?.map( ({img , location , distance})=>(
          <ExploreCards
          key={location}
          img={img}
          location={location}
          distance={distance}
          />
        )
        )}
        </div>
      </section>
      <section>
        <h1 className='text-3xl font-bold py-2'>live anywhere.</h1>
        <div className='flex overflow-x-scroll scrollbar-hide rounded-lg space-x-2'>
        {exploreBigCards?.map(({img,title})=>(
          <OptionCards
          key={title}
          img={img}
          title={title}
          />
        ))}
        </div>
      </section>
      <div className='text-center'>
      <LargeCard 
      title="best outdoor places"
      desc="choose your dream place"
      img="https://links.papareact.com/4cj"
      buttonText="get started"
      />
      </div>
    </main>
    <TheFooter/>
    </div>
  )
}

export async function getStaticProps () {
  const explore = await fetch("https://www.jsonkeeper.com/b/4G1G").then
  (
    res=>res.json()
  )
const exploreBigCards=await fetch("https://www.jsonkeeper.com/b/VHHT").then((response=>response.json()))
  return {
  props:{
    explore,
    exploreBigCards,
  }
}
}


